name: health_example
description: Demonstrates how to use the health plugin.
publish_to: "none"
version: 4.5.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  carp_serializable: ^2.0.0 # polymorphic json serialization
  healthBackwardsCompatible:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
